MACRO(ADD_SUBDIRS)
  FILE(GLOB sub_dirs RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *)
  FOREACH(dir IN LISTS sub_dirs)
    IF (IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
      IF (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${dir}/CMakeLists.txt)
        add_subdirectory(${dir})
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDMACRO()

MACRO(ADD_TEST)
  file(GLOB file_list "test_*.cpp")

  foreach(fname IN LISTS file_list)
    get_filename_component(basename ${fname} NAME_WE)
    add_executable(${module_name}_${basename} ${fname})
  endforeach()
ENDMACRO()  
